# Generated by Django 5.1.6 on 2025-02-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_playlists', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='play_count',
            field=models.IntegerField(default=0),
        ),
    ]
