# Generated by Django 5.1.6 on 2025-02-28 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_alter_song_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='genres',
            new_name='genre',
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='music.genre'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.artist'),
        ),
    ]
