# Generated by Django 5.1.6 on 2025-03-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_rename_genres_song_genre_alter_album_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
