# Generated by Django 5.1.6 on 2025-03-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_song_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
